version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./teampasswordmanager:/var/www/html/teampasswordmanager
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: teampasswordmanager
      MYSQL_USER: tpmuser
      MYSQL_PASSWORD: tpmpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
